Not Working

diff --git a/start b/start
--- a/start
+++ b/start
@@ -62,6 +62,22 @@ case $opt in
 echo ""
 echo "Write the new changes to this line without entering the AP Brand :"
 echo ""
+echo "------- Available Reaver switches fallowed in config -------->"
+echo ""
+echo "-p = Use the specified pin (may be arbitrary string or 4/8 digit WPS pin)"
+echo "-d = Set the delay between pin attempts | Default [1]"
+echo "-l = Set the time to wait if the AP locks WPS pin attempts | Default [60]"
+echo "-r = Sleep for y seconds every x pin attempts"
+echo "-t = Set the receive timeout period | Default [5]"
+echo "-T = Set the M5/M7 timeout period | Default [0.20]"
+echo "-N = Do not send NACK messages when out of order packets are received"
+echo "-S = Use small DH keys to improve crack speed"
+echo "-E = Terminate each WPS session with an EAP FAIL packet"
+echo "-n = Target AP always sends a NACK | Default [Auto] (options: True | False | Auto)"
+echo "-w = Mimic a Windows 7 registrar | Default [False] (options: True | False)"
+echo ""
+echo "------------------------------------------------------------->"
+echo ""
 echo "Existing line : $edt"
 echo -n "Edit to : "
 read edit
@@ -160,6 +176,22 @@ y|Y|YES|yes)
 echo ""
 echo "Please write all the switches for reaver excluding interface|bssid|channel"
 echo ""
+echo "------- Available Reaver switches allowed in config -------->"
+echo ""
+echo "-p = Use the specified pin (may be arbitrary string or 4/8 digit WPS pin)"
+echo "-d = Set the delay between pin attempts | Default [1]"
+echo "-l = Set the time to wait if the AP locks WPS pin attempts | Default [60]"
+echo "-r = Sleep for y seconds every x pin attempts"
+echo "-t = Set the receive timeout period | Default [5]"
+echo "-T = Set the M5/M7 timeout period | Default [0.20]"
+echo "-N = Do not send NACK messages when out of order packets are received"
+echo "-S = Use small DH keys to improve crack speed"
+echo "-E = Terminate each WPS session with an EAP FAIL packet"
+echo "-n = Target AP always sends a NACK | Default [Auto] (options: True | False | Auto)"
+echo "-w = Mimic a Windows 7 registrar | Default [False] (options: True | False)"
+echo ""
+echo "------------------------------------------------------------->"
+echo ""
 echo "Example 1 with direct pin : -p 12345678 -d 2 -N -E"
 echo "Example 2 : -t 10 -T 0.60 -N -E -w -K"
 echo ""
@@ -196,12 +228,35 @@ y|Y|YES|yes)
 echo ""
 echo "Please write all the switches for reaver excluding interface|bssid|channel"
 echo ""
+echo "------- Available Reaver switches allowed in config -------->"
+echo ""
+echo "-p = Use the specified pin (may be arbitrary string or 4/8 digit WPS pin)"
+echo "-d = Set the delay between pin attempts | Default [1]"
+echo "-l = Set the time to wait if the AP locks WPS pin attempts | Default [60]"
+echo "-r = Sleep for y seconds every x pin attempts"
+echo "-t = Set the receive timeout period | Default [5]"
+echo "-T = Set the M5/M7 timeout period | Default [0.20]"
+echo "-N = Do not send NACK messages when out of order packets are received"
+echo "-S = Use small DH keys to improve crack speed"
+echo "-E = Terminate each WPS session with an EAP FAIL packet"
+echo "-n = Target AP always sends a NACK | Default [Auto] (options: True | False | Auto)"
+echo "-w = Mimic a Windows 7 registrar | Default [False] (options: True | False)"
+echo ""
+echo "------------------------------------------------------------->"
+echo ""
 echo "Example 1 with direct pin : -p 12345678 -d 2 -N -E"
-echo "Example 2 : -t 10 -T 0.60 -N -E -w -K"
+echo "Example 2 : -t 10 -T 0.60 -N -E -w "
 echo ""
 echo "Write the switches for $gman"
 echo -n "Switches : "
 read swt
+if [[ -z "$swt" ]]
+then
+echo "Empty input , exiting"
+sleep 3
+delf
+exit 1
+fi
 echo "$gman $swt" > $path/database
 ;;
 n|N|NO|no)
